### ISSUE TITLE
How exactly do module blocks reference each other?

### ISSUE THREAD

**Issue by trusktr** [tc39/proposal-module-fragments#19]
The module blocks proposal includes an example which this proposal did not show a solution for:

```js
const countBlock = module {
  let i = 0;

  export function count() {
    i++;
    return i;
  }
};

const uppercaseBlock = module {
  export function uppercase(string) {
    return string.toUpperCase();
  }
};

const combinedBlock = module {
  const { count } = await import(countBlock);
  const { uppercase } = await import(uppercaseBlock);

  console.log(count()); // 1
  console.log(uppercase("daniel")); // "DANIEL"
};

// ReferenceError as we can't close over countBlock or uppercaseBlock!!
```

Is rewriting `const countBlock = module {` to `module countBlock {` the solution? It makes the identifier for the module in scope of other module blocks? If not, then how is it done?

You also mentioned import maps referencing module fragments. How?

**Comment by nicolo-ribaudo** [comment]
That example would be rewritten like this:
```js
module countBlock {
  let i = 0;

  export function count() {
    i++;
    return i;
  }
};

module uppercaseBlock {
  export function uppercase(string) {
    return string.toUpperCase();
  }
};

module combinedBlock {
  import { count } from countBlock;
  import { uppercase } from uppercaseBlock;

  console.log(count()); // 1
  console.log(uppercase("daniel")); // "DANIEL"
};
```

> You also mentioned import maps referencing module fragments. How?

An older version of the proposal used string-based module fragments names, that could be referenced with `file/url#fragment-id`; it's possible that the imports map mention is a leftover of that design :thinking:
